#!/usr/bin/python
import sys, os, re, errno, optparse, gzip, bz2, stat, string

#TODO recursive mode should ignore ENOENTs, those are just races
#between listdir() and open()

def shouldSkip(dirname, filename, options):
    if filename in ['.svn',
                    '.git',
                    'SCCS', 'BitKeeper',
                    'CVS',
                    '_darcs',
                    '.bzr',
                    '.sconsign',
                    '.sconsign.dblite',
                    '_trial_temp',
                    'dropin.cache',
                    '.hg',
                    '_go_.6',
                    ]:
        return True
    if (filename.endswith('~')
        or filename.startswith('.#')
        or (filename.startswith('#')
            and filename.endswith('#'))):
        return True

    nogz = filename
    if nogz.endswith('.gz'):
        nogz = filename[:-len('.gz')]
    elif nogz.endswith('.bz2'):
        nogz = filename[:-len('.bz2')]

    if (nogz.endswith('.pyc')
        or nogz.endswith('.pyo')
        or nogz.endswith('.elc')
        or nogz.endswith('.ps')
        or nogz.endswith('.dvi')
        or nogz.endswith('.pdf')
        or nogz.endswith('.png')
        or nogz.endswith('.jpg')
        or nogz.endswith('.dia')
        or nogz.endswith('.o')
        or nogz.endswith('.a')
        or nogz.endswith('.so')
        or nogz.endswith('.ko')
        or nogz.endswith('.gif')
        or nogz.endswith('.psd')
        or nogz.endswith('.mov')
        or nogz.endswith('.avi')
        or nogz.endswith('.wmv')
        or nogz.endswith('.ogg')
        or nogz.endswith('.ogv')
        or nogz.endswith('.mp3')
        or nogz.endswith('.swf')
        or nogz.endswith('.db')
        or nogz.endswith('.pcap')
        or nogz.endswith('.pickle')
        or nogz.endswith('.hi')
        or nogz.endswith('.egg')
        ):
        return True

    if dirname is None:
        path = filename
    else:
        path = os.path.join(dirname, filename)
    for pattern in options.exclude:
        if re.search(pattern, path):
            return True

    st = os.lstat(path)
    if (stat.S_ISSOCK(st.st_mode)
        or stat.S_ISBLK(st.st_mode)
        or stat.S_ISCHR(st.st_mode)
        or stat.S_ISFIFO(st.st_mode)
        ):
        return True

def write(line):
    try:
        sys.stdout.write(line)
    except IOError, e:
        if e.errno == errno.EPIPE:
            try:
                sys.stdout.close()
            except IOError, e:
                if e.errno == errno.EPIPE:
                    pass
                else:
                    raise
            sys.exit(0)
        else:
            print >>sys.stderr, "%s: %s" % (sys.argv[0], e)
            sys.exit(1)

def callback(state, dirname, fnames):
    fnames[:] = [fname for fname in fnames
                 if not shouldSkip(dirname, fname, state['options'])]

    for filename in sorted(fnames):
        if dirname is None:
            path = filename
        else:
            path = os.path.join(dirname, filename)
        matches = 0

        if filename.endswith('.gz'):
            opener = gzip.open
        elif filename.endswith('.bz2'):
            opener = bz2.BZ2File
        else:
            opener = file
        try:
            f=opener(path)
        except IOError, e:
            if e.errno in [errno.EISDIR, errno.ENOENT]:
                pass
            else:
                print >>sys.stderr, "%s: %s: %s" % (sys.argv[0], e, path)
        else:
            try:
                lineNumber = 0
                while True:
                    try:
                        line = f.readline()
                    except IOError, e:
                        print >>sys.stderr, "%s: %s: %s" % (sys.argv[0], e, path)
                        break
                    if not line:
                        break

                    lineNumber += 1
                    if state['regex'].search(line):
                        matches += 1
                        if state['options'].files_with_matches:
                            write('%s\n' % path)
                            break
                        if state['options'].filenames:
                            printable = True
                            for c in line:
                                if c not in string.printable:
                                    printable = False
                                    break
                            if printable:
                                line = '%s:%d:%s' % (path, lineNumber, line)
                            else:
                                line = '%s:%d\n' % (path, lineNumber)
                        write(line)
            finally:
                f.close()

            state['matches'] += matches
            if matches:
                state['matching-files'] += 1

def grapple(path, state):
    if not shouldSkip(None, path, state['options']):
        if os.path.isdir(path):
            os.path.walk(path, callback, state)
        else:
            callback(state, None, [path])

def main():
    parser = optparse.OptionParser()
    parser.set_usage('%prog [options] REGEX [PATH..]')
    parser.add_option('-i', '--ignore-case',
                      action='store_true',
                      help='ignore case distinctions')
    parser.add_option('-e', '--exclude',
                      action='append',
                      default=[],
                      help='files or directories that match PATTERN will be skipped',
                      metavar='PATTERN')
    parser.add_option('-l', '--files-with-matches',
                      action='store_true',
                      help='only print FILE names containing no match')
    parser.add_option('', '--no-filename',
                      action='store_false',
                      default=True,
                      dest='filenames',
                      help='do not show file names')
##     parser.add_option('-L', '--files-without-match',
##                       action='store_true',
##                       help='only print FILE names containing no match')
    options, args = parser.parse_args()

    if not args:
        parser.print_usage()
        sys.exit(1)

    flags = 0
    if options.ignore_case:
        flags = flags | re.IGNORECASE

    regex = re.compile(args[0], flags)
    state = {'regex': regex,
             'options': options,
             'matches': 0,
             'matching-files': 0,
             }
    if args[1:]:
        for path in args[1:]:
            grapple(path, state)
    else:
        for filename in sorted(os.listdir('.')):
            grapple(filename, state)

    if not options.files_with_matches:
        print '# matches: %d' % state['matches']
    print '# matching-files: %d' % state['matching-files']


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(1)
